CREATE TABLE Contact
(
	Id INTEGER NOT NULL IDENTITY(1, 1) CONSTRAINT Contact_PK PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	BirthDate DATETIME NULL,
	Email VARCHAR(50) NOT NULL,
	Address VARCHAR(100) NULL,
	Phone VARCHAR(11) NULL,
)

CREATE TABLE UserLogin
(
	UserName VARCHAR(20) NOT NULL CONSTRAINT UserLogin_PK PRIMARY KEY,
	Password VARCHAR(250) NOT NULL
)

INSERT INTO UserLogin VALUES ('admin', 'hvZeKKdU4acbLflANhWmxDbDLEKnWhDQKBOWG4bx5Cg=')